liminal-ai-security/liminal-sdk-python

.github/release-drafter.yml
.github/workflows/draft-release-notes.yml
.github/workflows/label-pull-request.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: update Release Drafter to use CalVer

---

.github/workflows/create-release-pr.yml
.github/workflows/label-pull-request.yml
.github/workflows/lint-and-analyze.yml
.github/workflows/lint-pull-request.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: fix additional release PR workflow issues

---

.github/workflows/label-pull-request.yml
.github/workflows/lint-and-analyze.yml
.github/workflows/lint-pull-request.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: ensure hooks can run in release PRs

---

.github/release-drafter.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: ensure `release` PRs are skipped by Release Drafter

---

.github/workflows/lint-and-analyze.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: fix too-strict branch target

---

.github/workflows/create-release.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: fix missing git config info in release workflow

---

.github/labeler.yml
.github/workflows/create-release-pr.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: use action to add `release` label to release PRs

---

pyproject.toml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

build: use `liminal-sdk-python` as the package name

---

poetry.lock
pyproject.toml

Our current pin will actually prevent this from being installed under Python 3.12.
N/A
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```

build: loosen Python version pin

---

README.md

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

docs: fix incorrect badges

---

README.md

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

docs: add installation instructions to README.md

---

pyproject.toml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

build: fix incorrect package source inclusion

---

.pre-commit-config.yaml
examples/__init__.py
examples/chat_client.py
examples/hydrate_response.py
examples/quickstart_with_microsoft.py
liminal/client.py
liminal/endpoints/auth/__init__.py
liminal/endpoints/auth/models.py
liminal/endpoints/llm/__init__.py
liminal/endpoints/prompt/__init__.py
liminal/endpoints/thread/__init__.py
liminal/helpers/model.py
poetry.lock
pyproject.toml
tests/__init__.py
tests/common.py

This PR:
- Updates which `ruff` and `pylint` linters are used (and runs them)
- Removes three redundant `pre-commit` hooks
N/A
<details>
```
Version 1.1
Suite D4700
have …
```

ci: update linters and hooks

---

README.md

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

docs: remove unnecessary logging in README examples

---

examples/chat_client.py
examples/hydrate_response.py
examples/quickstart_with_microsoft.py
liminal/client.py
liminal/const.py
liminal/endpoints/auth/__init__.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: add missing types

---

liminal/client.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

fix: ensure refresh token skips request lock

---

pyproject.toml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: remove redundant `pylint` rule

---

README.md

quick path update in readme for setup script
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: update readme path for script

---

README.md

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

docs: add example of creating a `Client` from a refresh token

---

README.md

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

docs: add connection pooling + TOC to docs

---

renovate.json

[SSIA][ssia]. Fixes #115 
N/A
<details>
```
Version 1.1
Suite D4700
(b) The …
```

fix: correct misspelling in Renovate config

---

liminal/endpoints/auth/models.py
liminal/endpoints/llm/models.py
liminal/endpoints/prompt/models.py
liminal/endpoints/thread/models.py
liminal/helpers/model.py
tests/test_llm.py
tests/test_thread.py

As part of this PR, we now return UTC-aware `datetime.datetime` objects for any timestamps (as opposed to ISO8601 strings).
[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```

refactor: more accurately align response types to Liminal API spec

---

.github/pull_request_template.md

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

docs: add "Breaking Changes" section to PR template

---

.github/labeler.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: adjust paths for auto-labeler

---

README.md
examples/chat_client.py
examples/hydrate_response.py
examples/quickstart_with_microsoft.py
liminal/auth/__init__.py
liminal/auth/microsoft/__init__.py
liminal/auth/microsoft/device_code_flow.py
liminal/auth/microsoft/models.py
liminal/client.py
tests/auth/test_liminal.py
tests/auth/test_microsoft.py
tests/conftest.py
tests/test_client.py

The PR renames `MicrosoftAuthProvider` to `DeviceCodeFlowProvider` to reflect its implementation more accurately. Furthermore, this object nows lives under `liminal.auth`; imports must be updated accordingly.
The existing `MicrosoftAuthProvider` class is really an implementation of am MS device code flow provider. In anticipation of supporting other MS providers in the future, this PR refactors things for clarity.
N/A
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```

refactor: refactor MS Device Code Flow provider structure

---

liminal/client.py
liminal/const.py
liminal/endpoints/prompt/__init__.py
liminal/endpoints/thread/__init__.py
tests/auth/test_liminal.py
tests/conftest.py
tests/test_client.py
tests/test_llm.py
tests/test_prompt.py
tests/test_thread.py

- Accommodate breaking change from Liminal API server
N/A
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```

fix: threads source usage

---

README.md
examples/chat_client.py
examples/hydrate_response.py
examples/quickstart_with_microsoft.py
liminal/endpoints/prompt/__init__.py
liminal/endpoints/prompt/models.py
tests/auth/test_liminal.py
tests/test_prompt.py

Accommodate breaking change from Liminal API server
N/A
<details>
```
Version 1.1
Suite D4700
indicated in the …
```

fix: use prompts module

---

liminal/endpoints/prompt/__init__.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

fix: prompts endpoints require source

---

pyproject.toml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: main into development 

---

liminal/endpoints/llm/models.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

refactor: remove google providers

---

.github/workflows/create-release-pr.yml
.github/workflows/create-release.yml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: enable beta releases in CI

---

liminal/auth/microsoft/models.py
liminal/endpoints/llm/__init__.py
liminal/endpoints/llm/models.py
liminal/endpoints/llm/schemas.py
liminal/endpoints/prompt/__init__.py
liminal/endpoints/prompt/models.py
liminal/endpoints/prompt/schemas.py
liminal/endpoints/thread/__init__.py
liminal/endpoints/thread/models.py
liminal/endpoints/thread/schemas.py
liminal/helpers/schema.py
tests/fixtures/model-instances-response.json
tests/fixtures/prompt-analyze-response.json
tests/fixtures/prompt-cleanse-response.json
tests/fixtures/prompt-hydrate-response.json
tests/fixtures/prompt-submit-response.json
tests/fixtures/threads-create-response.json
tests/fixtures/threads-deidentified-context-history-response.json
tests/fixtures/threads-get-available-response.json
tests/fixtures/threads-get-by-id-response.json

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

refactor: alter internal API schemas to match new Liminal API standard

---

poetry.lock
pyproject.toml

- [SSIA][ssia]
- For reference: https://github.com/astral-sh/ruff-lsp
N/A
<details>
```
Version 1.1
Suite D4700 …
```

build: add `ruff-lsp` to dev dependencies

---

.github/workflows/create-release-pr.yml

It's not worth having a grotesque amount of logic in place to calculate the next release version when we can just provided during the PR creation process.
N/A
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```

ci: simplify GH action to cut release PR

---

liminal/client.py
pyproject.toml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

ci: run hooks and fix issues

---

liminal/client.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

fix: re-add missing default request timeout

---

CODE_OF_CONDUCT
liminal/endpoints/prompt/models.py
liminal/endpoints/thread/__init__.py
tests/fixtures/prompt-cleanse-response.json
tests/fixtures/prompt-hydrate-response.json
tests/fixtures/prompt-submit-response.json

https://github.com/liminal-ai-security/liminal/pull/1354 caused a mismatch in what the data models for hydrate and cleanse responses expected.
hydrate_response.py example should be able to be ran successfully without InvalidFieldValue exception.
<details>
```
Version 1.1
Suite D4700
By making …
```

refactor: update data models to fit new api changes

---

liminal/endpoints/prompt/models.py

Not sure if this is the way to go but regression finally runs with this fix.
N/A
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```

fix: remove text field from reidentification token dataclass

---

liminal/endpoints/llm/models.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

feat: add Google Vertex AI as a supported provider

---

tests/conftest.py
tests/test_prompt.py

This allows us to remove an almost entirely redundant tests via some `pytest` fixture magic.
N/A
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```

refactor: consolidate streaming tests

---

liminal/endpoints/prompt/models.py
tests/fixtures/prompt-analyze-response.json

- Removes the `origin` field from `AnalysisFinding`
[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

fix!: remove `origin`

---

.github/pull_request_template.md

- [SSIA][ssia]
- I noticed the PR template was mentioning `main` as the default branch of the repo when it's actually `development`
N/A
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```

docs: update default branch in PR template

---

pyproject.toml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

build: update `pyproject.toml` to latest standard

---

pyproject.toml

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

build: update `pyproject.toml` to match current Liminal standards

---

liminal/endpoints/llm/__init__.py
liminal/endpoints/llm/models.py
tests/fixtures/model-instances-response.json
tests/fixtures/threads-create-response.json
tests/fixtures/threads-get-available-response.json
tests/fixtures/threads-get-by-id-response.json

- `ModelInstance`'s `model_connection` field -> `model_connections`
- BEFORE: `model_connection: ModelConnection | None`
- AFTER: `model_connections: list[ModelConnection]`
N/A
<details>
```
Version 1.1
Suite D4700 …
```

feat: add support for multiple model connections

---

renovate.json

Fixes #115.
N/A
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best
of my …
```

fix: fix error in Renovate config

---

liminal/client.py
tests/auth/test_liminal.py
tests/auth/test_microsoft.py
tests/test_client.py
tests/test_llm.py
tests/test_prompt.py
tests/test_thread.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: run hooks

---

liminal/endpoints/llm/models.py
liminal/endpoints/thread/models.py
tests/fixtures/model-instances-response.json
tests/fixtures/threads-create-response.json
tests/fixtures/threads-get-available-response.json
tests/fixtures/threads-get-by-id-response.json
tests/test_llm.py

- [SSIA][ssia]
- Some new fields have been added to `ModelInstance` & `Thread`
N/A
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```

feat: update model types

---

liminal/endpoints/llm/models.py

Regression is breaking against `development` and the culprit seems to be that the SDK doesn't recognize the new provider added.
N/A
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```

fix: Add google AI studio key

---

liminal/endpoints/thread/models.py
tests/fixtures/threads-get-available-response.json

- Removes `Chat` fields that aren't meant to be accessed by our clients
- `deidentified_text`
- `hashed_deidentified_input`
[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```

refactor: remove internal `Chat` fields

---

liminal/client.py
poetry.lock
pyproject.toml

- This PR attempts to finally fix our issues with Renovate only wanting the latest Python 3.12 version.
- We now stipulate that we want anything larger than 3.11 _and_ smaller than 3.12.
- The larger changes to `pyproject.toml` are merely formatting.
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: ensure correct supported Python versions

---

renovate.json

- This is another attempt to halt Renovate from shrinking our supported Python ranges.
N/A
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```

chore: update Renovate to replace `python` version (preserving range)

---

tests/fixtures/model-instances-response.json
tests/fixtures/threads-get-available-response.json
tests/fixtures/threads-get-by-id-response.json

Updates `ModelInstance` test data with new/changed allowed teams/users fields
N/A
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```

test: update `ModelInstance` test data

---

poetry.lock
pyproject.toml

N/A
Minor change to update sub-dependency version pins to remove identified security vulnerabilities in the current version of the sub-dependency. [Fix for LD-976](https://liminalai.atlassian.net/browse/LD-976).
N/A
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```

fix: Pin Sub-Dependency Version for Security Update

---

renovate.json

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

build: don't pin versions of certain packages

---

liminal/endpoints/llm/models.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

feat: add Microsoft Copilot Studio as a supported provider

---

.pre-commit-config.yaml
tests/conftest.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: update hook config and run hooks

---

liminal/endpoints/llm/models.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

feat: add support for Groq

---

.github/workflows/test.yml
.mise.toml
README.md
pyproject.toml
uv.lock

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

feat: officially support Python 3.13

---

.github/workflows/create-release-pr.yml
.github/workflows/create-release.yml
.github/workflows/lint-and-analyze.yml
.github/workflows/test.yml
pyproject.toml
uv.lock

- #373 missed several GitHub Actions that use a specific version of `uv`.
- This PR ties everything to `pyproject.toml`.
N/A
<details>
```
Version 1.1
Suite D4700
have the …
```

build: be more inclusive about bumping `uv` version

---

pyproject.toml
uv.lock

- Liminal uses `pydrive2` under the hood, which has [yet to update](https://github.com/iterative/PyDrive2/issues/369) to `cryptography` 44.0.0.
N/A
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in …
```

chore(deps): downgrade `cryptography` to 43.0.3

---

liminal/endpoints/llm/models.py
uv.lock

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

feat: add support for DeepSeek and xAI

---

pyproject.toml
tests/common.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

style: update `ruff` config to match 0.9.3

---

renovate.json

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

build: ensure Renovate uses the `chore` Conventional Commit type

---

.github/workflows/lint-and-analyze.yml

- `tj-actions/changed-files` was reported compromised this evening: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
- Interestingly, the malicious code was only injected into a specific commit within the main repo's tags; that commit does _not_ exist in the repo's `main` branch.
- To mitigate this, we forked a (confirmed clean) fork of the repo to under `liminal-ai-security` control.
- This PR makes the necessary replacement.
N/A
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```

refactor: replace compromised `tj-actions/changed-files` with clean fork

---

liminal/endpoints/llm/models.py

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

feat: add IBM watsonx as a supported provider

---

liminal/endpoints/prompt/models.py
tests/fixtures/prompt-analyze-response.json

[SSIA][ssia]
N/A
<details>
```
Version 1.1
Suite D4700 …
```

chore: update analysis findings schema to match latest Liminal API spec
